### ISSUE TITLE
程序bug

### ISSUE THREAD

**Issue by yuanjilai** [Herb-Sun/OKKLineSwift#1]
模拟器，iPhone 6s, iOS10.1(14B72)。点击MA与BOLL之间的EMA按钮时，程序崩溃在OKKLineMainView.swift（Line 303）。
堆栈信息:2016-12-31 16:07:12.425559 OKKLineSwift-iOS-Demo[2299:154750] [] nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available, dumping backtrace:
        [x86_64] libnetcore-856.20.4
    0   libsystem_network.dylib             0x000000011149c682 __nw_create_backtrace_string + 123
    1   libnetwork.dylib                    0x0000000111779932 nw_socket_add_input_handler + 3100
    2   libnetwork.dylib                    0x00000001117574f4 nw_endpoint_flow_attach_protocols + 3768
    3   libnetwork.dylib                    0x0000000111756511 nw_endpoint_flow_setup_socket + 563
    4   libnetwork.dylib                    0x0000000111755270 -[NWConcrete_nw_endpoint_flow startWithHandler:] + 2612
    5   libnetwork.dylib                    0x000000011177044d nw_endpoint_handler_path_change + 1261
    6   libnetwork.dylib                    0x000000011176fe7c nw_endpoint_handler_start + 570
    7   libnetwork.dylib                    0x0000000111787ae5 nw_endpoint_resolver_start_next_child + 2240
    8   libdispatch.dylib                   0x0000000111219980 _dispatch_call_block_and_release + 12
    9   libdispatch.dylib                   0x00000001112430cd _dispatch_client_callout + 8
    10  libdispatch.dylib                   0x0000000111220e6b _dispatch_queue_serial_drain + 236
    11  libdispatch.dylib                   0x0000000111221b9f _dispatch_queue_invoke + 1073
    12  libdispatch.dylib                   0x00000001112243b7 _dispatch_root_queue_drain + 720
    13  libdispatch.dylib                   0x000000011122408b _dispatch_worker_thread3 + 123
    14  libsystem_pthread.dylib             0x00000001115ec4de _pthread_wqthread + 1129
    15  libsystem_pthread.dylib             0x00000001115ea341 start_wqthread + 13
POST https://www.btc123.com/kline/klineapi?size=300&symbol=okcoincnbtccny&type=5min 200
fatal error: Index out of range

**Comment by Herb-Sun** [comment]
谢谢 我在iPhone 6s上测试了一下没有发现你说的那个bug,不过我会继续努力找 谢谢

**Comment by Herb-Sun** [comment]
我已经解决了您提的bug 再次感谢
